# Choisir une image de base python
FROM python:3.10-slim

# Créer un répertoire de travail
WORKDIR /app

# Copier tout le code du frontend dans l'image
COPY . .

# Installer les dépendances nécessaires
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port 8501 pour Streamlit
EXPOSE 8501

# Démarrer l'application Streamlit avec home.py comme fichier d'entrée
CMD ["streamlit", "run", "home.py", "--server.port=8501", "--server.address=0.0.0.0"]