version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - flix_network
    volumes:
      - db_data:/app/data
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    networks:
      - flix_network
    volumes:
      - db_data:/app/data
    depends_on:
      - backend

  database:
    image: qldrsc/duckdb:latest
    volumes:
      - db_data:/data/db_data
    networks:
      - flix_network

networks:
  flix_network:
    driver: bridge

volumes:
  db_data: