# Choisir une image de base python
FROM python:3.10-slim

# Créer un répertoire de travail
WORKDIR /app

# Copier tout le code du backend dans l'image
COPY . .

# Installer les dépendances nécessaires
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port 8000 pour FastAPI
EXPOSE 8000

# Démarrer l'API FastAPI avec uvicorn
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]